Troels awsome branch
AlexanderNorup/WorldOfZuulProject pull request #49
Opened 2020-11-06 09:10 UTC by TKalo

2020-11-06 13:33 UTC, AlexanderNorup commented on worldofzuul/PlayerType.java
> +            tempHappiness -= 80 * (1 - (totalProtein-proteinMin)/(proteinGoal-proteinMin));
ProteinGoal, og proteinMin KAN være 0 (hvis altså calorieMin el. calorieGoal er 0).  Så der skal være 0 checks.

2020-11-06 13:36 UTC, AlexanderNorup commented on worldofzuul/PlayerType.java
> +        happiness -= Math.max((1 - (totalCalories - calorieMin) / (calorieGoal - calorieMin)) * 10,0);
Samme her. Hvis calorieGoal og calorieMin er 0, så dividere vi med 0 her.

2020-11-06 13:36 UTC, AlexanderNorup commented on worldofzuul/PlayerType.java
> +        System.out.println("Calorie happiness: " + Math.max((1 - (totalCalories - calorieMin) / (calorieGoal - calorieMin)) * 10,0));
- og her.

2020-11-06 13:37 UTC, AlexanderNorup requested changes
Der mangler lidt 0 checks rundt omkring, så vi ikke får NaN eller INT_MAX igen. 

Ellers ser det mega fancy ud. Mega fedt lavet.

2020-11-10 12:14 UTC, magnuskjaer approved these changes

2020-11-10 12:15 UTC, merged